create table if not exists public.product_taxonomy (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('category', 'subCategory')),
  value text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (kind, value)
);

create or replace function public.set_product_taxonomy_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_product_taxonomy_updated_at on public.product_taxonomy;

create trigger set_product_taxonomy_updated_at
before update on public.product_taxonomy
for each row
execute function public.set_product_taxonomy_updated_at();
